/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.CTSachDAO;
import DAO.TacGiaChiTietDAO;
import DAO.TacGiaDAO;
import Entity.CTSach;
import Entity.TacGia;
import Entity.TacGiaChiTiet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import utils.MsgBox;

/**
 *
 * @author ADMIN
 */
public class TacGiaForm extends javax.swing.JPanel {

    /**
     * Creates new form TacGiaForm
     */
    TacGiaDAO daotg = new TacGiaDAO();
    List<TacGia> listtg = new ArrayList<>();
    TacGiaChiTietDAO daotgct = new TacGiaChiTietDAO();
    List<TacGiaChiTiet> listtgct = new ArrayList<>();
    CTSachDAO daocts = new CTSachDAO();
    List<CTSach> listcts ;
    int row = -1;
    

    public TacGiaForm() {
        initComponents();
        init();
    }

    private void init() {
        fillComboBox();
        fillTableTG();
        fillTableTGCT();
    }

    private void showInforTG() {
        String MaTG = (String) tblTacgia.getValueAt(this.row, 0);
        TacGia tg = daotg.selectById(MaTG);
        this.setFormTG(tg);
    }

    private void setFormTG(TacGia tg) {
        txtMaTG.setText(tg.getMaTG());
        txtTenTG.setText(tg.getTenTG());
        if (tg.getTrangThai() == 1) {
            rdbHDTG.setSelected(true);
        } else {
            rdbUnHDTG.setSelected(true);
        }
    }

    private TacGia getFormTG() {
        TacGia tg = new TacGia();
        tg.setMaTG(txtMaTG.getText());
        tg.setTenTG(txtTenTG.getText());
        if (rdbHDTG.isSelected()) {
            tg.setTrangThai(1);
        } else {
            tg.setTrangThai(0);
        }
        return tg;
    }

    private void setFormTGCT(TacGiaChiTiet tgct) {
        txtMaTGCT.setText(tgct.getMaTGCT());
        if (tgct.getTrangThai() == 1) {
            rdbHDTGCT.setSelected(true);
        } else {
            rdbUnHDTGCT.setSelected(true);
        }
    }

    private TacGiaChiTiet getFormTGCT() {
        TacGiaChiTiet tgct = new TacGiaChiTiet();
        String macts = (String) cbbMaCTS.getSelectedItem();
        tgct.setMaTGCT(txtMaTGCT.getText());
        tgct.setMaTG(txtMaTG.getText());
        tgct.setMaCTS(macts);
        if (rdbHDTGCT.isSelected()) {
            tgct.setTrangThai(1);
        } else {
            tgct.setTrangThai(0);
        }
        return tgct;
    }

    private void showInforTGCT() {
        String MaTGCT = (String) tblTacgiact.getValueAt(this.row, 0);
        TacGiaChiTiet tgct = daotgct.selectById(MaTGCT);
        this.setFormTGCT(tgct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTacgia = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        rdbUnHDTG = new javax.swing.JRadioButton();
        btnCleanTG = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTacgiact = new javax.swing.JTable();
        cbbMaCTS = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnThemTGCT = new javax.swing.JButton();
        txtMaTG = new javax.swing.JTextField();
        txtTenTG = new javax.swing.JTextField();
        rdbHDTG = new javax.swing.JRadioButton();
        btnInsertTG = new javax.swing.JButton();
        btnUpdateTG = new javax.swing.JButton();
        btnUpdateTGCT = new javax.swing.JButton();
        txtMaTGCT = new javax.swing.JTextField();
        rdbHDTGCT = new javax.swing.JRadioButton();
        rdbUnHDTGCT = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("Mã Tác Giả");

        jLabel5.setText("Tên Tác Giả");

        tblTacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Tác Giả", "Tên Tác Giả", "Bút Danh", "Địa Chỉ", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTacgia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacgiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTacgia);

        jLabel6.setText("Trạng Thái");

        buttonGroup1.add(rdbUnHDTG);
        rdbUnHDTG.setText("Đang Ẩn");

        btnCleanTG.setText("Mới");
        btnCleanTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanTGActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã Chi Tiết Tác Giả");

        tblTacgiact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaTGCT", "Mã Tác Giả", "Mã Chi Tiết Sách", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTacgiact.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTacgiact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTacgiactMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTacgiact);

        cbbMaCTS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMaCTSItemStateChanged(evt);
            }
        });

        jLabel8.setText("Mã Chi Tiết Sách");

        btnThemTGCT.setText("Thêm");
        btnThemTGCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTGCTActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbHDTG);
        rdbHDTG.setText("Đang hoạt động");

        btnInsertTG.setText("Thêm");
        btnInsertTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertTGActionPerformed(evt);
            }
        });

        btnUpdateTG.setText("Sửa");
        btnUpdateTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTGActionPerformed(evt);
            }
        });

        btnUpdateTGCT.setText("Sửa");
        btnUpdateTGCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTGCTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdbHDTGCT);
        rdbHDTGCT.setText("Đang hoạt động");

        buttonGroup2.add(rdbUnHDTGCT);
        rdbUnHDTGCT.setText("Đang ẩn");

        jLabel1.setText("Trạng Thái");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaTG))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdbHDTG)
                                        .addGap(34, 34, 34)
                                        .addComponent(rdbUnHDTG)
                                        .addGap(23, 23, 23))
                                    .addComponent(txtTenTG))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCleanTG, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnInsertTG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateTG)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbMaCTS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaTGCT)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbHDTGCT)
                            .addComponent(rdbUnHDTGCT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnThemTGCT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnUpdateTGCT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertTG)
                    .addComponent(btnUpdateTG))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanTG))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbUnHDTG)
                        .addComponent(rdbHDTG)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbbMaCTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbHDTGCT)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTGCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnThemTGCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateTGCT)
                            .addComponent(rdbUnHDTGCT))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacgiaMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tblTacgia.getSelectedRow();
            this.showInforTG();
        }
    }//GEN-LAST:event_tblTacgiaMouseClicked

    private void btnInsertTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertTGActionPerformed
        insert();
    }//GEN-LAST:event_btnInsertTGActionPerformed

    private void btnUpdateTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTGActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateTGActionPerformed

    private void btnCleanTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanTGActionPerformed
        clearFrom();
    }//GEN-LAST:event_btnCleanTGActionPerformed

    private void tblTacgiactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTacgiactMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tblTacgiact.getSelectedRow();
            this.showInforTGCT();
        }
    }//GEN-LAST:event_tblTacgiactMouseClicked

    private void cbbMaCTSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMaCTSItemStateChanged
        fillTableTGCT();
    }//GEN-LAST:event_cbbMaCTSItemStateChanged

    private void btnThemTGCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTGCTActionPerformed
        insertTGCT();
    }//GEN-LAST:event_btnThemTGCTActionPerformed

    private void btnUpdateTGCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTGCTActionPerformed
        updateTGCT();
    }//GEN-LAST:event_btnUpdateTGCTActionPerformed

    void clearFrom() {
        TacGia tg = new TacGia();
        this.setFormTG(tg);
        this.row = -1;
    }

    private void insert() {
        TacGia tg = getFormTG();
        try {
            daotg.insert(tg);
            this.fillTableTG();
            this.clearFrom();
            tblTacgia.setRowSelectionInterval(tblTacgia.getRowCount() - 1, tblTacgia.getRowCount() - 1);
            MsgBox.alert(this, "Thêm thành công" + tg.getMaTG());
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm thất bại");
            e.printStackTrace();
        }
    }

    private void update() {
        TacGia tg = getFormTG();
        try {
            daotg.update(tg);
            fillTableTG();
            tblTacgia.setRowSelectionInterval(row, row);
            MsgBox.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại");
        }
    }
    private void insertTGCT(){
        TacGiaChiTiet tgct = getFormTGCT();
        try {
            daotgct.insert(tgct);
            fillTableTGCT();
            MsgBox.alert(this, "Thêm thành công");
        } catch (Exception e) {
             MsgBox.alert(this, "Thêm thành công");
             e.printStackTrace();
        }
    }
    private void updateTGCT() {
        TacGiaChiTiet tgct = getFormTGCT();
        try {
            daotgct.update(tgct);
            fillTableTGCT();
            MsgBox.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanTG;
    private javax.swing.JButton btnInsertTG;
    private javax.swing.JButton btnThemTGCT;
    private javax.swing.JButton btnUpdateTG;
    private javax.swing.JButton btnUpdateTGCT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbMaCTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdbHDTG;
    private javax.swing.JRadioButton rdbHDTGCT;
    private javax.swing.JRadioButton rdbUnHDTG;
    private javax.swing.JRadioButton rdbUnHDTGCT;
    private javax.swing.JTable tblTacgia;
    private javax.swing.JTable tblTacgiact;
    private javax.swing.JTextField txtMaTG;
    private javax.swing.JTextField txtMaTGCT;
    private javax.swing.JTextField txtTenTG;
    // End of variables declaration//GEN-END:variables

    private void fillTableTG() {
        DefaultTableModel tableModel = (DefaultTableModel) tblTacgia.getModel();
        tableModel.setRowCount(0);
        try {
            listtg = daotg.selecALL();
            listtg.stream().forEach((tg) -> {
                tableModel.addRow(new Object[]{
                    tg.getMaTG(), tg.getTenTG(), tg.getButDanh(), tg.getDiaChi(), tg.getTrangThai() == 1 ? "Đang hoạt động" : "Đang Ẩn"
                });
            });
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
            e.printStackTrace();
        }
    }

    private void fillTableTGCT() {
        DefaultTableModel model = (DefaultTableModel) tblTacgiact.getModel();
        model.setRowCount(0);
        try {
            String cts = (String) cbbMaCTS.getSelectedItem();
            listtgct = daotgct.selectbyCTSach(cts);
            for(TacGiaChiTiet tgct : listtgct){
                model.addRow(new Object[]{
                    tgct.getMaTGCT(), 
                    tgct.getMaTG(),
                    tgct.getMaCTS(), 
                    tgct.getTrangThai() == 1 ? "Đang hoạt động" : "Đang Ẩn"
                });
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
            e.printStackTrace();
        }
    }

    private void fillComboBox() {
        DefaultComboBoxModel cbbModel =(DefaultComboBoxModel) cbbMaCTS.getModel();
        cbbModel.removeAllElements();
        listcts =daocts.selecALL();
        for(CTSach cts : listcts){
            cbbMaCTS.addItem(cts.getMaCTS()+"");
        }
    }
}
